spring:
  application:
    name: Java_Tax_Free_project

  datasource:
    url: jdbc:postgresql://localhost:5432/tax_free_db
    username: postgres
    password: Avinas542610*
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

logging:
  level:
    org.springframework.security: DEBUG

server:
  servlet:
    session:
      timeout: 5m