package project.enums;

//ISO-3166 Alpha 2 non-EU countries including EU countries with third territories
public enum EUTerritoriesWithNonEUCountries {
    AF("Afghanistan", "Afganistanas"),
    AX("Aland Islands", "Alandai"),
    AL("Albania", "Albanija"),
    DZ("Algeria", "Alžyras"),
    AS("American Samoa", "Amerikos Samoa"),
    AD("Andorra", "Andora"),
    AO("Angola", "Angola"),
    AI("Anguilla", "Angilija"),
    AQ("Antarctica", "Antarktida"),
    AG("Antigua and Barbuda", "Antigva ir Barbuda"),
    AR("Argentina", "Argentina"),
    AM("Armenia", "Armėnija"),
    AW("Aruba", "Aruba"),
    AU("Australia", "Australija"),
    AZ("Azerbaijan", "Azerbaidžanas"),
    BS("Bahamas", "Bahamos"),
    BH("Bahrain", "Bahreinas"),
    BD("Bangladesh", "Bangladešas"),
    BB("Barbados", "Barbadosas"),
    BY("Belarus", "Baltarusija"),
    BZ("Belize", "Belizas"),
    BJ("Benin", "Beninas"),
    BM("Bermuda", "Bermuda"),
    BT("Bhutan", "Butanas"),
    BO("Bolivia", "Bolivija"),
    BA("Bosnia and Herzegovina", "Bosnija ir Hercegovina"),
    BW("Botswana", "Botsvana"),
    BV("Bouvet Island", "Buvė"),
    BR("Brazil", "Brazilija"),
    IO("British Indian Ocean Territory", "Indijos vandenyno britų salos"),
    VG("British Virgin Islands", "Mergelių Salos (Didžioji Britanija)"),
    BN("Brunei", "Brunėjus"),
    BF("Burkina Faso", "Burkina Fasas"),
    BI("Burundi", "Burundis"),
    KH("Cambodia", "Kambodža"),
    CM("Cameroon", "Kamerūnas"),
    CA("Canada", "Kanada"),
    CV("Cape Verde", "Žaliasis Kyšulys"),
    BQ("Caribbean Netherlands", "Karibų Nyderlandai"),
    KY("Cayman Islands", "Kaimanų salos"),
    CF("Central African Republic", "Centrinės Afrikos Respublika"),
    TD("Chad", "Čadas"),
    CL("Chile", "Čilė"),
    CN("China", "Kinija"),
    CX("Christmas Island", "Kalėdų sala"),
    CC("Cocos (Keeling) Islands", "Kokosų salos"),
    CO("Colombia", "Kolumbija"),
    KM("Comoros", "Komorai"),
    CG("Congo", "Kongo Respublika"),
    CK("Cook Islands", "Kuko salos"),
    CR("Costa Rica", "Kosta Rika"),
    CU("Cuba", "Kuba"),
    CW("Curacao", "Kiurasao"),
    CD("Democratic Republic of the Congo", "Kongo Demokratinė Respublika"),
    DJ("Djibouti", "Džibutis"),
    DM("Dominica", "Dominika"),
    DO("Dominican Republic", "Dominikos Respublika"),
    EC("Ecuador", "Ekvadoras"),
    EG("Egypt", "Egiptas"),
    SV("El Salvador", "Salvadoras"),
    GQ("Equatorial Guinea", "Pusiaujo Gvinėja"),
    ER("Eritrea", "Eritrėja"),
    SZ("Eswatini", "Esvatinis"),
    ET("Ethiopia", "Etiopija"),
    FK("Falkland Islands", "Falklando salos"),
    FO("Faroe Islands", "Farerai"),
    FM("Federated States of Micronesia", "Mikronezijos Federacinės Valstijos"),
    FJ("Fiji", "Fidžis"),
    FI("Finland", "Suomija"),
    FR("France", "Prancūzija"),
    GF("French Guiana", "Prancūzijos Gviana"),
    PF("French Polynesia", "Prancūzijos Polinezija"),
    TF("French Southern Territories", "Prancūzijos Pietų Sritys"),
    GA("Gabon", "Gabonas"),
    GM("Gambia", "Gambija"),
    GE("Georgia", "Gruzija"),
    DE("Germany", "Vokietija"),
    GH("Ghana", "Gana"),
    GI("Gibraltar", "Gibraltaras"),
    GR("Greece", "Graikija"),
    GL("Greenland", "Grenlandija"),
    GD("Grenada", "Grenada"),
    GP("Guadeloupe", "Gvadelupa"),
    GU("Guam", "Guamas"),
    GT("Guatemala", "Gvatemala"),
    GG("Guernsey", "Gernsis"),
    GN("Guinea", "Gvinėja"),
    GW("Guinea-Bissau", "Bisau Gvinėja"),
    GY("Guyana", "Gajana"),
    HT("Haiti", "Haitis"),
    HM("Heard Island and McDonald Islands", "Herdo ir Makdonaldo salos"),
    HN("Honduras", "Hondūras"),
    HK("Hong Kong", "Honkongas"),
    IS("Iceland", "Islandija"),
    IN("India", "Indija"),
    ID("Indonesia", "Indonezija"),
    IR("Iran", "Iranas"),
    IQ("Iraq", "Irakas"),
    IM("Isle of Man", "Meno sala"),
    IL("Israel", "Izraelis"),
    IT("Italy", "Italija"),
    CI("Ivory Coast", "Dramblio Kaulo Krantas"),
    JM("Jamaica", "Jamaika"),
    JP("Japan", "Japonija"),
    JE("Jersey", "Džersis"),
    JO("Jordan", "Jordanija"),
    KZ("Kazakhstan", "Kazachstanas"),
    KE("Kenya", "Kenija"),
    KI("Kiribati", "Kiribatis"),
    KW("Kuwait", "Kuveitas"),
    KG("Kyrgyzstan", "Kirgizija"),
    LA("Laos", "Laosas"),
    LB("Lebanon", "Libanas"),
    LS("Lesotho", "Lesotas"),
    LR("Liberia", "Liberija"),
    LY("Libya", "Libija"),
    LI("Liechtenstein", "Lichtenšteinas"),
    MO("Macau", "Makao"),
    MK("North Macedonia", "Šiaurės Makedonija"),
    MG("Madagascar", "Madagaskaras"),
    MW("Malawi", "Malavis"),
    MY("Malaysia", "Malaizija"),
    MV("Maldives", "Maldyvai"),
    ML("Mali", "Malis"),
    MH("Marshall Islands", "Maršalo salos"),
    MQ("Martinique", "Martinika"),
    MR("Mauritania", "Mauritanija"),
    MU("Mauritius", "Mauricijus"),
    YT("Mayotte", "Majotas"),
    MX("Mexico", "Meksika"),
    MD("Moldova", "Moldavija"),
    MC("Monaco", "Monakas"),
    MN("Mongolia", "Mongolija"),
    ME("Montenegro", "Juodkalnija"),
    MS("Montserrat", "Montseratas"),
    MA("Morocco", "Marokas"),
    MZ("Mozambique", "Mozambikas"),
    MM("Myanmar", "Mianmaras"),
    NA("Namibia", "Namibija"),
    NR("Nauru", "Nauru"),
    NP("Nepal", "Nepalas"),
    NC("New Caledonia", "Naujoji Kaledonija"),
    NZ("New Zealand", "Naujoji Zelandija"),
    NI("Nicaragua", "Nikaragva"),
    NE("Niger", "Nigeris"),
    NG("Nigeria", "Nigerija"),
    NU("Niue", "Niujė"),
    NF("Norfolk Island", "Norfolko sala"),
    KP("North Korea", "Šiaurės Korėja"),
    MP("Northern Mariana Islands", "Marianos Šiaurinės Salos"),
    NO("Norway", "Norvegija"),
    OM("Oman", "Omanas"),
    PK("Pakistan", "Pakistanas"),
    PW("Palau", "Palau"),
    PS("Palestine", "Palestina"),
    PA("Panama", "Panama"),
    PG("Papua New Guinea", "Papua Naujoji Gvinėja"),
    PY("Paraguay", "Paragvajus"),
    PE("Peru", "Peru"),
    PH("Philippines", "Filipinai"),
    PN("Pitcairn Islands", "Pitkerno salos"),
    PR("Puerto Rico", "Puerto Rikas"),
    QA("Qatar", "Kataras"),
    RE("Reunion", "Reunjonas"),
    RU("Russia", "Rusija"),
    RW("Rwanda", "Ruanda"),
    BL("Saint Barthelemy", "Šv. Bartolomėjaus sala"),
    SH("Saint Helena", "Šv. Elenos sala"),
    KN("Saint Kitts and Nevis", "Sent Kitsas ir Nevis"),
    LC("Saint Lucia", "Sent Lusija"),
    MF("Saint Martin", "Sen Martenas"),
    PM("Saint Pierre and Miquelon", "Sen Pjeras ir Mikelonas"),
    VC("Saint Vincent and the Grenadines", "Sent Vinsentas ir Grenadinai"),
    WS("Samoa", "Samoa"),
    SM("San Marino", "San Marinas"),
    ST("Sao Tome and Principe", "San Tomė ir Principė"),
    SA("Saudi Arabia", "Saudo Arabija"),
    SN("Senegal", "Senegalas"),
    RS("Serbia", "Serbija"),
    SC("Seychelles", "Seišeliai"),
    SL("Sierra Leone", "Siera Leonė"),
    SG("Singapore", "Singapūras"),
    SX("Sint Maarten", "Sint Martenas"),
    SB("Solomon Islands", "Saliamono Salos"),
    SO("Somalia", "Somalis"),
    ZA("South Africa", "Pietų Afrikos Respublika"),
    GS("South Georgia and the South Sandwich Islands", "Pietų Džordžija ir Pietų Sandvičo salos"),
    KR("South Korea", "Pietų Korėja"),
    SS("South Sudan", "Pietų Sudanas"),
    ES("Spain", "Ispanija"),
    LK("Sri Lanka", "Šri Lanka"),
    SD("Sudan", "Sudanas"),
    SR("Suriname", "Surinamas"),
    SJ("Svalbard and Jan Mayen", "Svalbardas"),
    CH("Switzerland", "Šveicarija"),
    SY("Syria", "Sirija"),
    TW("Taiwan", "Taivanas"),
    TJ("Tajikistan", "Tadžikija"),
    TZ("Tanzania", "Tanzanija"),
    TH("Thailand", "Tailandas"),
    TL("Timor-Leste", "Rytų Timoras"),
    TG("Togo", "Togas"),
    TK("Tokelau", "Tokelau"),
    TO("Tonga", "Tonga"),
    TT("Trinidad and Tobago", "Trinidadas ir Tobagas"),
    TN("Tunisia", "Tunisas"),
    TR("Turkey", "Turkija"),
    TM("Turkmenistan", "Turkmėnija"),
    TC("Turks and Caicos Islands", "Terkso ir Kaikoso salos"),
    TV("Tuvalu", "Tuvalu"),
    UG("Uganda", "Uganda"),
    UA("Ukraine", "Ukraina"),
    AE("United Arab Emirates", "Jungtiniai Arabų Emyratai"),
    GB("United Kingdom", "Jungtinė Karalystė"),
    US("United States of America", "Jungtinės Amerikos Valstijos"),
    UM("United States Minor Outlying Islands", "Jungtinių Amerikos Valstijų mažosios aplinkinės salos"),
    VI("United States Virgin Islands", "Mergelių salos (JAV)"),
    UY("Uruguay", "Urugvajus"),
    UZ("Uzbekistan", "Uzbekija"),
    VU("Vanuatu", "Vanuatu"),
    VA("Vatican City", "Vatikanas"),
    VE("Venezuela", "Venesuela"),
    VN("Vietnam", "Vietnamas"),
    WF("Wallis and Futuna", "Volisas ir Futūna"),
    EH("Western Sahara", "Vakarų Sachara"),
    YE("Yemen", "Jemenas"),
    ZM("Zambia", "Zambija"),
    ZW("Zimbabwe", "Zimbabvė");

    private final String longEN;
    private final String longLT;

    EUTerritoriesWithNonEUCountries(final String longEN, final String longLT) {
        this.longEN = longEN;
        this.longLT = longLT;
    }

    public String getLongEN() {
        return longEN;
    }

    public String getLongLT() {
        return longLT;
    }
}
